Script started on 2017年03月13日 (週一) 21時52分45秒
]0;andrew@andrew-System-Product-Name: ~/桌面/lab1[01;32mandrew@andrew-System-Product-Name[00m:[01;34m~/桌面/lab1[00m$ git clone http://github.com/andrewwlin999/lab1.git[A]0;andrew@andrew-System-Product-Name: ~/桌面/lab1[01;32mandrew@andrew-System-Product-Name[00m:[01;34m~/桌面/lab1[00m$ [C[C[C[C[Config -l[K
[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[3Pwhoami;pwdvim questionb.cpp[7Pwhoami;pwdgit config -llone http://github.com/andrewwlin999/lab1.git[A]0;andrew@andrew-System-Product-Name: ~/桌面/lab1[01;32mandrew@andrew-System-Product-Name[00m:[01;34m~/桌面/lab1[00m$ [K
[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C./questionb
22
22
11
34
17
52
26
13
40
20
10
5
16
8
4
2
1
]0;andrew@andrew-System-Product-Name: ~/桌面/lab1[01;32mandrew@andrew-System-Product-Name[00m:[01;34m~/桌面/lab1[00m$ exit

Script done on 2017年03月13日 (週一) 21時53分35秒
